Neos:
  Neos:
    fusion:
      autoInclude:
        NeosRulez.Bootstrap.GalleryCarousel: true
    userInterface:
      translation:
        autoInclude:
          NeosRulez.Bootstrap.GalleryCarousel:
            - 'NodeTypes/Content/*'
